sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t ivanlee/docker-k8s -f Dockerfile.dev .

script:
  - docker run -e CI=true ivanlee/docker-k8s npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-3"
  app: "docker-test"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-3-034316087020"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"